ARG PYTHON_VERSION=3.13
FROM mcr.microsoft.com/devcontainers/python:${PYTHON_VERSION}

# Install additional packages if needed
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     <packages> \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*
